# coding: utf-8

"""
    Blogs API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.articles_list import ArticlesList  # noqa: E501
from swagger_client.rest import ApiException


class TestArticlesList(unittest.TestCase):
    """ArticlesList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testArticlesList(self):
        """Test ArticlesList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.articles_list.ArticlesList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
