# coding: utf-8

"""
    Blogs API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.blog_service_api import BlogServiceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestBlogServiceApi(unittest.TestCase):
    """BlogServiceApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.blog_service_api.BlogServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v1_articles_get(self):
        """Test case for api_v1_articles_get

        """
        pass

    def test_api_v1_articles_post(self):
        """Test case for api_v1_articles_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
